// Generated by Cursor.

using Azure.Messaging.ServiceBus;
using RedShirt.Example.JobWorker.JobManagement.AzureServiceBus.Models;
using RedShirt.Example.JobWorker.JobManagement.AzureServiceBus.Services;

namespace RedShirt.Example.JobWorker.JobManagement.AzureServiceBus.UnitTests.Tests.Services;

public class AzureServiceBusBodyStringRetrieverTests
{
    [Fact]
    public void GetBody_PreservesUtf8Content()
    {
        const string bodyText = "こんにちは 🌍";
        var receivedMessage = ServiceBusModelFactory.ServiceBusReceivedMessage(BinaryData.FromString(bodyText));
        var container = new Mock<IServiceBusMessageContainer>();
        container.SetupGet(c => c.Message).Returns(receivedMessage);

        var retriever = new AzureServiceBusBodyStringRetriever();

        var body = retriever.GetBody(container.Object);

        Assert.Equal(bodyText, body);
    }

    [Fact]
    public void GetBody_ReturnsEmptyString_WhenMessageBodyIsEmpty()
    {
        var receivedMessage = ServiceBusModelFactory.ServiceBusReceivedMessage(BinaryData.FromString(string.Empty));
        var container = new Mock<IServiceBusMessageContainer>();
        container.SetupGet(c => c.Message).Returns(receivedMessage);

        var retriever = new AzureServiceBusBodyStringRetriever();

        var body = retriever.GetBody(container.Object);

        Assert.Equal(string.Empty, body);
    }

    [Fact]
    public void GetBody_ReturnsMessageBodyAsString()
    {
        const string bodyText = "Hello World!";
        var receivedMessage = ServiceBusModelFactory.ServiceBusReceivedMessage(BinaryData.FromString(bodyText));
        var container = new Mock<IServiceBusMessageContainer>();
        container.SetupGet(c => c.Message).Returns(receivedMessage);

        var retriever = new AzureServiceBusBodyStringRetriever();

        var body = retriever.GetBody(container.Object);

        Assert.Equal(bodyText, body);
        container.VerifyGet(c => c.Message, Times.Once);
    }
}