<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RedShirt.Example.JobWorker.JobManagement.Common\RedShirt.Example.JobWorker.JobManagement.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Apache.NMS.ActiveMQ" Version="2.2.0" />
    </ItemGroup>


</Project>
