<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.Common.Aws\RedShirt.Example.JobWorker.Common.Aws.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.JobManagement.Common\RedShirt.Example.JobWorker.JobManagement.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.1.3"/>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.1"/>
        <PackageReference Include="AWSSDK.Kinesis" Version="4.0.2.4"/>
        <PackageReference Include="AWSSDK.SQS" Version="4.0.0.6"/>
        <PackageReference Include="DistributedLock.Redis" Version="1.1.0"/>
        <PackageReference Include="StackExchange.Redis" Version="2.8.37"/>
    </ItemGroup>

</Project>
