<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.Common.Aws.Sqs\RedShirt.Example.JobWorker.Common.Aws.Sqs.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.Common.Distributed\RedShirt.Example.JobWorker.Common.Distributed.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.Common.SecretManagers.Core\RedShirt.Example.JobWorker.Common.SecretManagers.Core.csproj"/>
        <ProjectReference Include="..\RedShirt.Example.JobWorker.Core\RedShirt.Example.JobWorker.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.4"/>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101"/>
        <PackageReference Include="AWSSDK.Kinesis" Version="4.0.101"/>
    </ItemGroup>

</Project>
