using RedShirt.Example.JobWorker.Core.Services.ExecutionState;

namespace RedShirt.Example.JobWorker.Core.UnitTests.Tests.Services.ExecutionState;

// Generated by Cursor
public class JobLoaderStateServiceTests
{
    /// <summary>
    ///     Concurrent start/stop/read calls should not throw and should eventually report finished.
    /// </summary>
    [Fact(Timeout = 2000)]
    public async Task TestConcurrentAccess_EventuallyFinished()
    {
        var service = new JobLoaderStateService();
        var cancellationToken = TestContext.Current.CancellationToken;

        var startTask = Task.Run(() =>
        {
            for (var i = 0; i < 100; i++)
            {
                service.ReportLoaderStart();
                _ = service.IsLoaderFinished();
            }
        }, cancellationToken);

        var stopTask = Task.Run(() =>
        {
            for (var i = 0; i < 100; i++)
            {
                service.ReportLoaderStop();
                _ = service.IsLoaderFinished();
            }
        }, cancellationToken);

        await Task.WhenAll(startTask, stopTask);

        Assert.True(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Reporting start alone is not enough; the loader must also report stop.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStartOnly_False()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();

        Assert.False(service.IsLoaderFinished());
    }

    [Fact]
    public void TestIsLoaderFinished_AfterStartThenStop_True()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Reporting stop without a prior start must not count as finished.
    ///     Consumers rely on this to avoid treating a never-started loader as done.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStopOnly_False()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStop();

        Assert.False(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Order of stop-then-start still yields finished once both have been reported.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStopThenStart_True()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStop();
        service.ReportLoaderStart();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestIsLoaderFinished_InitialState_False()
    {
        var service = new JobLoaderStateService();

        Assert.False(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Once both flags are set, finished stays true even if start is reported again.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_RemainsTrueAfterAdditionalStart()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.ReportLoaderStart();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestReportLoaderStart_IsIdempotent()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStart();

        Assert.False(service.IsLoaderFinished());

        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestReportLoaderStop_IsIdempotent()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }
}