using RedShirt.Example.JobWorker.Core.Services.ExecutionState;

namespace RedShirt.Example.JobWorker.Core.UnitTests.Tests.Services.ExecutionState;

// Generated by Cursor
public class JobLoaderStateServiceTests
{
    [Fact]
    public void AddOnFinishCallback_AfterStartAndStop_InvokesImmediately()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.AddOnFinishCallback(() => invocations++);

        Assert.Equal(1, invocations);
    }

    [Fact]
    public void AddOnFinishCallback_AfterStartOnly_DoesNotInvokeUntilStop()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;

        service.ReportLoaderStart();
        service.AddOnFinishCallback(() => invocations++);

        Assert.Equal(0, invocations);

        service.ReportLoaderStop();

        Assert.Equal(1, invocations);
    }

    [Fact]
    public void AddOnFinishCallback_AfterStopOnly_DoesNotInvokeUntilStart()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;

        service.ReportLoaderStop();
        service.AddOnFinishCallback(() => invocations++);

        Assert.Equal(0, invocations);

        service.ReportLoaderStart();

        Assert.Equal(1, invocations);
    }

    /// <summary>
    ///     Subscribers racing with start/stop must each run exactly once (immediate or deferred).
    /// </summary>
    [Fact(Timeout = 2000)]
    public async Task AddOnFinishCallback_ConcurrentSubscribe_EachRunsOnce()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;
        var cancellationToken = TestContext.Current.CancellationToken;
        const int subscriberCount = 64;

        var subscribeTask = Task.Run(() =>
        {
            Parallel.For(0, subscriberCount, new ParallelOptions {CancellationToken = cancellationToken},
                _ => service.AddOnFinishCallback(() => Interlocked.Increment(ref invocations)));
        }, cancellationToken);

        var reportTask = Task.Run(() =>
        {
            service.ReportLoaderStart();
            service.ReportLoaderStop();
        }, cancellationToken);

        await Task.WhenAll(subscribeTask, reportTask);

        Assert.Equal(subscriberCount, invocations);
        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void AddOnFinishCallback_InvokesRegisteredCallbacksOnce()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;

        service.AddOnFinishCallback(() => invocations++);
        service.AddOnFinishCallback(() => invocations++);

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.ReportLoaderStop();

        Assert.Equal(2, invocations);
    }

    [Fact(Timeout = 2000)]
    public async Task AddOnFinishCallback_IsThreadSafeAndRunsOnce()
    {
        var service = new JobLoaderStateService();
        var invocations = 0;
        var cancellationToken = TestContext.Current.CancellationToken;

        service.AddOnFinishCallback(() => Interlocked.Increment(ref invocations));

        await Task.WhenAll(
            Enumerable.Range(0, 32).Select(_ => Task.Run(() =>
            {
                service.ReportLoaderStart();
                service.ReportLoaderStop();
            }, cancellationToken)));

        Assert.Equal(1, invocations);
        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void AddOnFinishCallback_WhenNull_ThrowsArgumentNullException()
    {
        var service = new JobLoaderStateService();

        Assert.Throws<ArgumentNullException>(() => service.AddOnFinishCallback(null!));
    }

    /// <summary>
    ///     Concurrent start/stop/read calls should not throw and should eventually report finished.
    /// </summary>
    [Fact(Timeout = 2000)]
    public async Task TestConcurrentAccess_EventuallyFinished()
    {
        var service = new JobLoaderStateService();
        var cancellationToken = TestContext.Current.CancellationToken;

        var startTask = Task.Run(() =>
        {
            for (var i = 0; i < 100; i++)
            {
                service.ReportLoaderStart();
                _ = service.IsLoaderFinished();
            }
        }, cancellationToken);

        var stopTask = Task.Run(() =>
        {
            for (var i = 0; i < 100; i++)
            {
                service.ReportLoaderStop();
                _ = service.IsLoaderFinished();
            }
        }, cancellationToken);

        await Task.WhenAll(startTask, stopTask);

        Assert.True(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Reporting start alone is not enough; the loader must also report stop.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStartOnly_False()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();

        Assert.False(service.IsLoaderFinished());
    }

    [Fact]
    public void TestIsLoaderFinished_AfterStartThenStop_True()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Reporting stop without a prior start must not count as finished.
    ///     Consumers rely on this to avoid treating a never-started loader as done.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStopOnly_False()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStop();

        Assert.False(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Order of stop-then-start still yields finished once both have been reported.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_AfterStopThenStart_True()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStop();
        service.ReportLoaderStart();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestIsLoaderFinished_InitialState_False()
    {
        var service = new JobLoaderStateService();

        Assert.False(service.IsLoaderFinished());
    }

    /// <summary>
    ///     Once both flags are set, finished stays true even if start is reported again.
    /// </summary>
    [Fact]
    public void TestIsLoaderFinished_RemainsTrueAfterAdditionalStart()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.ReportLoaderStart();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestReportLoaderStart_IsIdempotent()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStart();

        Assert.False(service.IsLoaderFinished());

        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }

    [Fact]
    public void TestReportLoaderStop_IsIdempotent()
    {
        var service = new JobLoaderStateService();

        service.ReportLoaderStart();
        service.ReportLoaderStop();
        service.ReportLoaderStop();

        Assert.True(service.IsLoaderFinished());
    }
}